# Based on https://github.com/actions/starter-workflows/blob/03277899f01de35a7544217d1b02c1031bae1102/ci/rust.yml
name: CI

on:
  push:
    branches:
      - master
      - "feature/**"
  pull_request:
    branches:
      - master
      - "feature/**"

env:
  CARGO_TERM_COLOR: always

  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  fmt_lint_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: davidB/rust-cargo-make@v1
    - uses: actions/checkout@v4
    - name: Run CI flow
      run: cargo make ci-flow
