# Based on https://github.com/actions/starter-workflows/blob/03277899f01de35a7544217d1b02c1031bae1102/ci/rust.yml
name: CI

on:
  push:
    branches:
      - master
      - "feature/**"
  pull_request:
    branches:
      - master
      - "feature/**"

env:
  CARGO_TERM_COLOR: always

  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_test_fmt_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Rustfmt
      # see https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server
      run: cargo fmt --all -- --check
    - name: Run Clippy
      # see https://doc.rust-lang.org/clippy/continuous_integration/github_actions.html
      run: cargo clippy --all-targets --all-features
