# Based on https://github.com/actions/starter-workflows/blob/03277899f01de35a7544217d1b02c1031bae1102/ci/rust.yml
name: CI

on:
  push:
    branches:
      - master
      - "feature/**"
  pull_request:
    branches:
      - master
      - "feature/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
